/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scifi.gltf --transform
Files: scifi.gltf [335.72MB] > scifi-transformed.glb [3.88MB] (99%)
*/

import React from 'react'
import { PerspectiveCamera, useGLTF } from '@react-three/drei'

export function Scifi(props) {
  const { nodes, materials } = useGLTF('../scifi-transformed.glb')
  return (
    <group
      {...props}
      dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={4.2}
        fov={27.108}
        position={[-1.317, 1.943, -12.976]}
        rotation={[3.133, -0.009, 3.142]} />

      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={7.1}
        fov={28.409}
        position={[8.096, 2.686, -12.792]}
        rotation={[-3.092, 0.508, 3.118]} />

      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={7.2}
        fov={25.918}
        position={[-11.027, 2.573, -7.649]}
        rotation={[Math.PI, -0.633, Math.PI]} />

      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={7.2}
        fov={25.918}
        position={[-7.564, 2.105, -6.326]}
        rotation={[3.138, -0.678, 3.139]} />

      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={4}
        fov={25.918}
        position={[-0.689, 2.04, 2.751]}
        rotation={[-0.119, -0.923, -0.095]} />

      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={7.2}
        fov={25.918}
        position={[-8.111, 2.055, -2.582]}
        rotation={[-3.054, -1.137, -3.062]} />

      <group
        position={[0, 0.067, 8.796]}
        rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          geometry={nodes.SM_Wall_Window_Inset_8x4003_1.geometry}
          material={materials.emmisive} />

        <mesh
          geometry={nodes.SM_Wall_Window_Inset_8x4003_2.geometry}
          material={materials.universal} />
      </group>

      <group
        position={[-5.879, 0.067, -11.703]}
        rotation={[0, -1.571, 0]}>
        <mesh
          geometry={nodes.SM_Wall_Angle_IN_1x4003_1.geometry}
          material={materials.emmisive} />

        <mesh
          geometry={nodes.SM_Wall_Angle_IN_1x4003_2.geometry}
          material={materials.universal} />
      </group>

      <mesh
        geometry={nodes.Circle016.geometry}
        material={materials['Material.009']}
        position={[0.005, 0.07, 0.007]} />

      <mesh
        castShadow
        geometry={nodes.Circle017.geometry}
        material={materials['Material.001']}
        position={[0, 0, 0]} />

      <mesh
        geometry={nodes.Plane031.geometry}
        material={materials['Material.010']}
        position={[-0.398, 1.669, 4.56]}
        rotation={[Math.PI / 2, 0, 0.041]} />

      <mesh
        geometry={nodes.Circle018.geometry}
        material={materials._Emissive}
        position={[0, 4.566, 0]} />

      <mesh
        geometry={nodes.Circle019.geometry}
        material={materials['Material.007']}
        position={[-0.011, 4.588, 0.006]}
        scale={2.761} />

      <mesh
        geometry={nodes.Circle022.geometry}
        material={materials['Material.003']}
        position={[2.334, -0.215, 13.708]}
        rotation={[0, 0.109, 0]} />

      <mesh
        geometry={nodes.Plane032.geometry}
        material={materials.sf2_panel_04}
        position={[0, 4.629, -1.25]} />

      <mesh
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials.Material}
        position={[0.046, 0.055, 0.022]} />

      <mesh
        geometry={nodes.Ob_Circular1_1_Cube003.geometry}
        material={materials.universal}
        position={[-0.007, 0.193, 1.04]}
        scale={0.405} />
    </group>
  )
}

useGLTF.preload('../scifi-transformed.glb')
